version: "3"

services:
    node:
        build: docker-node
        tty: true
        volumes:
            - .:/storage/current
            - ../../:/storage/projects
        ports:
            - '8080:8080'
        expose:
            - '8080'
