version: 2
jobs:
  lint:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - restore_cache:
          keys:
            - npm-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: npm-{{ checksum "package.json" }}
      - run: npm run lint
  build:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - restore_cache:
          keys:
          - npm-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          paths:
          - node_modules
          key: npm-{{ checksum "package.json" }}
      - run: npm run build
  deploy:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - restore_cache:
          keys:
            - npm-{{ checksum "package.json" }}
      - add_ssh_keys:
          fingerprints:
            - ${ SSHKEYS_FINGERPRINTS }
      - run: npm install
      - run: git config user.name $GITHUB_NAME
      - run: git config user.email $GITHUB_EMAIL
      - run: npm run deploy
workflows:
  version: 2
  build-deploy:
    jobs:
      - lint
      - build:
          requires:
            - lint
          filters:
            branches:
              only: master
      - deploy:
          requires:
            - build
            
          filters:
            branches:
              only: master