version: 2
jobs:
  lint:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - restore_cache:
          keys:
            - npm-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: npm-{{ checksum "package.json" }}
      - run: npm run lint
  build-deploy:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - restore_cache:
          keys:
            - npm-{{ checksum "package.json" }}
      - add_ssh_keys:
          fingerprints:
            - "d4:2d:85:6c:75:e7:26:60:03:d7:14:37:3f:3a:54:d6"
      - run: npm install
      - run: npm run build
      - run: git config user.name $GITHUB_NAME
      - run: git config user.email $GITHUB_EMAIL
      - run: cp CNAME docs/CNAME
      - run: npm run deploy
workflows:
  version: 2
  lint-build-deploy:
    jobs:
      - lint
      - build-deploy:
          requires:
            - lint
          filters:
            branches:
              only: master